name: tag

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  validate:
    uses: ./.github/workflows/validate.yml

  publish:
    needs: validate
    timeout-minutes: 9
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: 'https://registry.npmjs.org'

      - run: npm i

      - name: npm release
        env:
          NODE_AUTH_TOKEN: ${{secrets.KOA_BODY_NPM_TOKEN}}
        run: |
          npm publish
